# Generated by Django 5.1.2 on 2024-10-13 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_remove_review_course_coursereview_delete_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='coursereview',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='reviews', to='reviews.tag'),
        ),
    ]
