# Generated by Django 5.1.2 on 2024-11-29 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_alter_review_options_alter_review_difficulty_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='exam_format',
            field=models.CharField(choices=[('mcq_only', 'MCQ Only'), ('essay_only', 'Essay Only'), ('mcq_and_essay', 'MCQ and Essay')], default='mcq_only', max_length=20),
        ),
        migrations.AlterField(
            model_name='review',
            name='attendance_mandatory',
            field=models.BooleanField(default=False),
        ),
    ]
