# Generated by Django 5.1.2 on 2024-11-29 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_review_exam_format_alter_review_attendance_mandatory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='exam_format',
            field=models.CharField(choices=[('mcq_only', 'MCQ Only'), ('short_answer_only', 'Short Answer Only'), ('mcq_and_short_answer', 'MCQ and Short Answer')], default='mcq_only', max_length=25),
        ),
    ]
