# Generated by Django 5.1.2 on 2024-10-13 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('instructor', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(default='DEFAULT_CODE', max_length=20)),
            ],
        ),
    ]
