# Generated by Django 5.1.2 on 2024-11-13 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(default='DEFAULT_CATEGORY', max_length=100),
        ),
    ]
