from django.core.management.base import BaseCommand
from courses.models import Course

class Command(BaseCommand):
    help = 'Add predefined courses to the database'

    def handle(self, *args, **kwargs):
        # List of courses
        courses = [
            {"code": "BIOA01H3", "title": "Life on Earth: Unifying Principles"},
            {"code": "BIOA02H3", "title": "Life on Earth: Form, Function and Interactions"},
            {"code": "BIOA11H3", "title": "Introduction to the Biology of Humans"},
            {"code": "BIOA12H3", "title": "Introduction to the Biology of Humans"},
            {"code": "BIOA13H3", "title": "Biology of Humans Laboratory"},
            {"code": "BIOA14H3", "title": "Biology of Humans Laboratory"},
            {"code": "BIOB01H3", "title": "Introduction to Molecular and Cellular Biology"},
            {"code": "BIOB02H3", "title": "Introduction to Molecular and Cellular Biology"},
            {"code": "BIOB11H3", "title": "Introduction to the Biology of Organisms"},
            {"code": "BIOB12H3", "title": "Introduction to the Biology of Organisms"},
            {"code": "BIOB13H3", "title": "Biology of Organisms Laboratory"},
            {"code": "BIOB14H3", "title": "Biology of Organisms Laboratory"},
            {"code": "BIOC01H3", "title": "Fundamentals of Biochemistry"},
            {"code": "BIOC02H3", "title": "Fundamentals of Biochemistry"},
            {"code": "BIOC11H3", "title": "Biochemistry of Metabolism"},
            {"code": "BIOC12H3", "title": "Biochemistry of Metabolism"},
            {"code": "BIOC13H3", "title": "Biochemistry Laboratory"},
            {"code": "BIOC14H3", "title": "Biochemistry Laboratory"},
            {"code": "BIOD01H3", "title": "Evolution"},
            {"code": "BIOD02H3", "title": "Evolution"},
            {"code": "BIOD11H3", "title": "Introduction to Ecology and Evolution"},
            {"code": "BIOD12H3", "title": "Introduction to Ecology and Evolution"},
            {"code": "BIOD21H3", "title": "Biogeography"},
            {"code": "BIOD22H3", "title": "Conservation Biology"},
            {"code": "BIOD23H3", "title": "Behavioral Ecology"},
            {"code": "BIOD24H3", "title": "Population Ecology"},
            {"code": "BIOD25H3", "title": "Community Ecology"},
            {"code": "BIOD26H3", "title": "Ecosystem Ecology"},
            {"code": "BIOD27H3", "title": "Biodiversity"},
            {"code": "BIOD28H3", "title": "Ecology of Infectious Diseases"},
            {"code": "BIOD29H3", "title": "Ecological Genetics"},
            {"code": "BIOD30H3", "title": "Invasion Biology"},
            {"code": "BIOD31H3", "title": "Marine Ecology"},
            {"code": "BIOD32H3", "title": "Freshwater Ecology"},
            {"code": "BIOD33H3", "title": "Plant Ecology"},
            {"code": "BIOD34H3", "title": "Comparative Animal Physiology"},
            {"code": "BIOD35H3", "title": "Physiology of Plants"},
            {"code": "BIOD36H3", "title": "Physiology of Animals"},
            {"code": "BIOD37H3", "title": "Physiology of Microorganisms"},
            {"code": "BIOD38H3", "title": "Microbial Ecology"},
            {"code": "BIOD39H3", "title": "Insect Ecology"},
            {"code": "BIOD40H3", "title": "Human Ecology"},
            {"code": "BIOD41H3", "title": "Plant Systematics"},
            {"code": "BIOD42H3", "title": "Animal Systematics"},
            {"code": "BIOD43H3", "title": "Fungal Systematics"},
            {"code": "BIOD44H3", "title": "Bacterial Systematics"},
            {"code": "BIOD45H3", "title": "Viruses and Virology"},
            {"code": "CSCA08H3", "title": "Introduction to Computer Science I"},
            {"code": "CSCA20H3", "title": "Introduction to Programming"},
            {"code": "CSCA48H3", "title": "Introduction to Computer Science II"},
            {"code": "CSCA67H3", "title": "Discrete Mathematics"},
            {"code": "CSCB07H3", "title": "Software Design"},
            {"code": "CSCB09H3", "title": "Software Tools and Systems Programming"},
            {"code": "CSCB20H3", "title": "Introduction to Databases and Web Applications"},
            {"code": "CSCB36H3", "title": "Introduction to the Theory of Computation"},
            {"code": "CSCB58H3", "title": "Computer Organization"},
            {"code": "CSCB63H3", "title": "Design and Analysis of Data Structures"},
            {"code": "CSCC01H3", "title": "Introduction to Software Engineering"},
            {"code": "CSCC09H3", "title": "Programming on the Web"},
            {"code": "CSCC10H3", "title": "Human-Computer Interaction"},
            {"code": "CSCC11H3", "title": "Introduction to Machine Learning and Data Mining"},
            {"code": "CSCC24H3", "title": "Principles of Programming Languages"},
            {"code": "CSCC37H3", "title": "Introduction to Numerical Algorithms for Computational Mathematics"},
            {"code": "CSCC43H3", "title": "Introduction to Databases"},
            {"code": "CSCC46H3", "title": "Social and Information Networks"},
            {"code": "CSCC63H3", "title": "Computability and Computational Complexity"},
            {"code": "CSCC69H3", "title": "Operating Systems"},
            {"code": "CSCC73H3", "title": "Algorithm Design and Analysis"},
            {"code": "CSCC85H3", "title": "Fundamentals of Robotics and Automated Systems"},
            {"code": "CSCD01H3", "title": "Engineering Large Software Systems"},
            {"code": "CSCD03H3", "title": "Social Impact of Information Technology"},
            {"code": "CSCD37H3", "title": "Analysis of Numerical Algorithms for Computational Mathematics"},
            {"code": "CSCD43H3", "title": "Database System Technology"},
            {"code": "CSCD54H3", "title": "Technology Innovation and Entrepreneurship"},
            {"code": "CSCD58H3", "title": "Computer Networks"},
            {"code": "CSCD70H3", "title": "Compiler Optimization"},
            {"code": "CSCD71H3", "title": "Topics in Computer Science"},
            {"code": "CSCD72H3", "title": "Topics in the Theory of Computing"},
            {"code": "CSCD84H3", "title": "Artificial Intelligence"},
            {"code": "CSCD90H3", "title": "The Startup Sandbox"},
            {"code": "CSCD92H3", "title": "Readings in Computer Science"},
            {"code": "CSCD94H3", "title": "Computer Science Project"},
            {"code": "CSCD95H3", "title": "Computer Science Project"},
            {"code": "MATA02H3", "title": "The Magic of Numbers"},
            {"code": "MATA22H3", "title": "Linear Algebra I for Mathematical Sciences"},
            {"code": "MATA23H3", "title": "Linear Algebra I"},
            {"code": "MATA29H3", "title": "Calculus I for the Life Sciences"},
            {"code": "MATA30H3", "title": "Calculus I for Physical Sciences"},
            {"code": "MATA31H3", "title": "Calculus I for Mathematical Sciences"},
            {"code": "MATA34H3", "title": "Calculus for Management"},
            {"code": "MATA35H3", "title": "Calculus II for Biological Sciences"},
            {"code": "MATA36H3", "title": "Calculus II for Physical Sciences"},
            {"code": "MATA37H3", "title": "Calculus II for Mathematical Sciences"},
            {"code": "MATA67H3", "title": "Discrete Mathematics"},
            {"code": "MATB24H3", "title": "Linear Algebra II"},
            {"code": "MATB41H3", "title": "Techniques of the Calculus of Several Variables I"},
            {"code": "MATB42H3", "title": "Techniques of the Calculus of Several Variables II"},
            {"code": "MATB43H3", "title": "Introduction to Analysis"},
            {"code": "MATB44H3", "title": "Differential Equations I"},
            {"code": "MATB61H3", "title": "Linear Programming and Optimization"},
            {"code": "MATC01H3", "title": "Groups and Symmetry"},
            {"code": "MATC09H3", "title": "Introduction to Mathematical Logic"},
            {"code": "MATC15H3", "title": "Introduction to Number Theory"},
            {"code": "MATC27H3", "title": "Introduction to Topology"},
            {"code": "MATC32H3", "title": "Graph Theory and Algorithms for its Applications"},
            {"code": "MATC34H3", "title": "Complex Variables"},
            {"code": "MATC37H3", "title": "Introduction to Real Analysis"},
            {"code": "MATC44H3", "title": "Introduction to Combinatorics"},
            {"code": "MATC46H3", "title": "Differential Equations II"},
            {"code": "MATC58H3", "title": "An Introduction to Mathematical Biology"},
            {"code": "MATC63H3", "title": "Differential Geometry"},
            {"code": "MATC82H3", "title": "Mathematics for Teachers"},
            {"code": "MATC90H3", "title": "Beginnings of Mathematics"},
            {"code": "MATD01H3", "title": "Fields and Groups"},
            {"code": "MATD02H3", "title": "Classical Plane Geometries and their Transformations"},
            {"code": "MATD09H3", "title": "Set Theory"},
            {"code": "MATD10H3", "title": "Topics in Mathematics"},
            {"code": "MATD11H3", "title": "Topics in Mathematics"},
            {"code": "MATD12H3", "title": "Topics in Mathematics"},
            {"code": "MATD16H3", "title": "Coding Theory and Cryptography"},
            {"code": "MATD26H3", "title": "Geometric Analysis and Relativity"},
            {"code": "MATD34H3", "title": "Complex Variables II"},
            {"code": "MATD35H3", "title": "Introduction to Discrete Dynamical Systems"},
            {"code": "MATD44H3", "title": "Topics in Combinatorics"},
            {"code": "MATD46H3", "title": "Partial Differential Equations"},
            {"code": "MATD50H3", "title": "Mathematical Introduction to Game Theory"},
            {"code": "MATD67H3", "title": "Differentiable Manifolds"},
            {"code": "MATD92H3", "title": "Mathematics Project"},
            {"code": "MATD93H3", "title": "Mathematics Project"},
            {"code": "MATD94H3", "title": "Readings in Mathematics"},
            {"code": "MATD95H3", "title": "Readings in Mathematics"},
            {"code": "MGAB01H3", "title": "Introductory Financial Accounting I"},
            {"code": "MGAB02H3", "title": "Introductory Financial Accounting II"},
            {"code": "MGAB03H3", "title": "Introductory Management Accounting"},
            {"code": "MGAC01H3", "title": "Intermediate Financial Accounting I"},
            {"code": "MGAC02H3", "title": "Intermediate Financial Accounting II"},
            {"code": "MGAC03H3", "title": "Intermediate Management Accounting"},
            {"code": "MGAC10H3", "title": "Auditing"},
            {"code": "MGAC50H3", "title": "Canadian Income Taxation I"},
            {"code": "MGAC70H3", "title": "Management Information Systems"},
            {"code": "MGAC80H3", "title": "Special Topics in Accounting"},
            {"code": "MGAD20H3", "title": "Advanced Auditing"},
            {"code": "MGAD40H3", "title": "Management Control Systems"},
            {"code": "MGAD45H3", "title": "Corporate Governance and Strategy - CPA Perspective"},
            {"code": "MGAD50H3", "title": "Advanced Financial Accounting"},
            {"code": "MGAD60H3", "title": "Controversial Issues in Accounting"},
            {"code": "MGAD65H3", "title": "Canadian Income Taxation II"},
            {"code": "MGAD70H3", "title": "Advanced Accounting Case Analysis: A Capstone Course"},
            {"code": "MGAD80H3", "title": "Accounting Issues in International Business"},
            {"code": "MGAD85H3", "title": "Advanced Special Topics in Accounting"},
            {"code": "MGFB10H3", "title": "Principles of Finance"},
            {"code": "MGFC10H3", "title": "Intermediate Finance"},
            {"code": "MGFC20H3", "title": "Personal Financial Management"},
            {"code": "MGFC30H3", "title": "Introduction to Derivatives Markets"},
            {"code": "MGFC35H3", "title": "Investments"},
            {"code": "MGFC45H3", "title": "Portfolio Management: Theory and Practice"},
            {"code": "MGFC50H3", "title": "International Financial Management"},
            {"code": "MGFC60H3", "title": "Financial Statement Analysis and Security Valuation"},
            {"code": "MGFC85H3", "title": "Special Topics in Finance"},
            {"code": "MGFD15H3", "title": "Private Equity"},
            {"code": "MGFD25H3", "title": "Financial Technologies and Applications (FinTech)"},
            {"code": "MGFD30H3", "title": "Risk Management"},
            {"code": "MGFD40H3", "title": "Investor Psychology and Behavioural Finance"},
            {"code": "MGFD50H3", "title": "Mergers and Acquisitions: Theory and Practice"},
            {"code": "MGFD60H3", "title": "Financial Modeling and Trading Strategies"},
            {"code": "MGFD70H3", "title": "Advanced Financial Management"},
            {"code": "MGFD85H3", "title": "Advanced Special Topics in Finance"},
            {"code": "MGHA12H3", "title": "Human Resource Management"},
            {"code": "MGHB02H3", "title": "Managing People and Groups in Organizations"},
            {"code": "MGHC02H3", "title": "Management Skills"},
            {"code": "MGHC23H3", "title": "Diversity in the Workplace"},
            {"code": "MGHC50H3", "title": "Special Topics in Human Resources"},
            {"code": "MGHC51H3", "title": "Special Topics in Organizational Behaviour"},
            {"code": "MGHC52H3", "title": "Business Negotiation"},
            {"code": "MGHC53H3", "title": "Introduction to Industrial Relations"},
            {"code": "MGHD14H3", "title": "Leadership"},
            {"code": "MGHD24H3", "title": "Occupational Health and Safety Management"},
            {"code": "MGHD25H3", "title": "Human Resources Recruitment and Selection"},
            {"code": "MGHD26H3", "title": "Training and Development"},
            {"code": "MGHD27H3", "title": "Human Resources Planning and Strategy"},
            {"code": "MGHD28H3", "title": "Compensation"},
            {"code": "MGHD60H3", "title": "Advanced Special Topics in Organizational Behaviour and Human Resources"},
            {"code": "MGIA01H3", "title": "Principles of International Marketing"},
            {"code": "MGIA12H3", "title": "International Human Resources"},
            {"code": "MGIB01H3", "title": "Global Marketing"},
            {"code": "MGIB02H3", "title": "International Organizational Behaviour"},
            {"code": "MGIC01H3", "title": "International Corporate Strategy"},
            {"code": "MGIC02H3", "title": "International Leadership Skills"},
            {"code": "MGID40H3", "title": "Introduction to International Business Law"},
            {"code": "MGID79H3", "title": "International Capstone Case Analysis"},
            {"code": "MGMA01H3", "title": "Principles of Marketing"},
            {"code": "MGMB01H3", "title": "Marketing Management"},
            {"code": "MGMC01H3", "title": "Market Research"},
            {"code": "MGMC02H3", "title": "Consumer Behaviour"},
            {"code": "MGMC11H3", "title": "Product Management and Branding"},
            {"code": "MGMC12H3", "title": "Advertising: From Theory to Practice"},
            {"code": "MGMC13H3", "title": "Pricing Strategy"},
            {"code": "MGMC14H3", "title": "Sales and Distribution Management"},
            {"code": "MGMC20H3", "title": "Marketing in the Information Age"},
            {"code": "MGMC30H3", "title": "Event and Sponsorship Management"},
            {"code": "MGMC40H3", "title": "Special Topics in Marketing"},
            {"code": "MGMD01H3", "title": "Applied Marketing Models"},
            {"code": "MGMD02H3", "title": "Judgement and Decision Making"},
            {"code": "MGMD10H3", "title": "Seminar in Consumer Psychology I"},
            {"code": "MGMD11H3", "title": "Seminar in Consumer Psychology II"},
            {"code": "MGMD19H3", "title": "Advanced Special Topics in Marketing II"},
            {"code": "MGMD20H3", "title": "Advanced Special Topics in Marketing I"},
            {"code": "MGMD21H3", "title": "Competitive Marketing in Action"},
            {"code": "MGOC10H3", "title": "Analytics for Decision Making"},
            {"code": "MGOC15H3", "title": "Introductory Business Data Analytics"},
            {"code": "MGOC20H3", "title": "Operations Management"},
            {"code": "MGOC50H3", "title": "Special Topics in Analytics and Operations"},
            {"code": "MGOD31H3", "title": "Advanced Business Data Analytics"},
            {"code": "MGOD40H3", "title": "Simulation and Analysis of Business Processes"},
            {"code": "MGOD50H3", "title": "Advanced Special Topics in Analytics and Operations Management"},
            {"code": "MGSB01H3", "title": "Introduction to Strategy"},
            {"code": "MGSB22H3", "title": "Entrepreneurship"},
            {"code": "MGSC01H3", "title": "Strategic Management I"},
            {"code": "MGSC03H3", "title": "Public Management"},
            {"code": "MGSC05H3", "title": "The Changing World of Business - Government Relations"},
            {"code": "MGSC07H3", "title": "Introduction to Case Analysis Techniques"},
            {"code": "MGSC10H3", "title": "Business Strategy in the Digital Age"},
            {"code": "MGSC12H3", "title": "Narrative and Management"},
            {"code": "MGSC14H3", "title": "Management Ethics"},
            {"code": "MGSC20H3", "title": "Consulting and Contracting: New Ways of Work"},
            {"code": "MGSC26H3", "title": "Venture Capital"},
            {"code": "MGSC30H3", "title": "The Legal Environment of Business I"},
            {"code": "MGSC35H3", "title": "Innovation"},
            {"code": "MGSC44H3", "title": "International Business Management"},
            {"code": "MGSC91H3", "title": "Special Topics in Strategy"},
            {"code": "MGSD01H3", "title": "Senior Seminar in Strategic Management"},
            {"code": "MGSD05H3", "title": "Strategic Management II"},
            {"code": "MGSD15H3", "title": "Managing in the Information Economy"},
            {"code": "MGSD24H3", "title": "New Venture Creation and Planning"},
            {"code": "MGSD30H3", "title": "Intellectual Property Law"},
            {"code": "MGSD32H3", "title": "The Legal Environment of Business II"},
            {"code": "MGSD40H3", "title": "Principles of Corporate Social Responsibility"},
            {"code": "MGSD55H3", "title": "Strategy and Technology"},
            {"code": "MGSD91H3", "title": "Advanced Special Topics in Strategy"},
            {"code": "MGTA01H3", "title": "Introduction to Business"},
            {"code": "MGTA02H3", "title": "Managing the Business Organization"},
            {"code": "MGTA38H3", "title": "Management Communications"},
            {"code": "MGTB60H3", "title": "Introduction to the Business of Sport"},
            {"code": "MGTC28H3", "title": "Computer Programming Applications for Business"},
            {"code": "MGTD80H3", "title": "Supervised Reading In Management"},
            {"code": "MGTD81H3", "title": "Supervised Reading In Management"},
            {"code": "MGTD82Y3", "title": "Supervised Reading In Management"},
            {"code": "PSYA01H3", "title": "Introduction to Biological and Cognitive Psychology"},
            {"code": "PSYA02H3", "title": "Introduction to Clinical, Developmental, Personality and Social Psychology"},
            {"code": "PSYB03H3", "title": "Introduction to Computers in Psychological Research"},
            {"code": "PSYB07H3", "title": "Data Analysis in Psychology"},
            {"code": "PSYB10H3", "title": "Introduction to Social Psychology"},
            {"code": "PSYB20H3", "title": "Introduction to Developmental Psychology"},
            {"code": "PSYB30H3", "title": "Introduction to Personality"},
            {"code": "PSYB32H3", "title": "Introduction to Clinical Psychology"},
            {"code": "PSYB38H3", "title": "Introduction to Behaviour Modification"},
            {"code": "PSYB51H3", "title": "Introduction to Perception"},
            {"code": "PSYB55H3", "title": "Introduction to Cognitive Neuroscience"},
            {"code": "PSYB57H3", "title": "Introduction to Cognitive Psychology"},
            {"code": "PSYB64H3", "title": "Introduction to Behavioural Neuroscience"},
            {"code": "PSYB70H3", "title": "Methods in Psychological Science"},
            {"code": "PSYB80H3", "title": "Psychology in Context"},
            {"code": "PSYB90H3", "title": "Supervised Introductory Research in Psychology"},
            {"code": "PSYC02H3", "title": "Scientific Communication in Psychology"},
            {"code": "PSYC03H3", "title": "Computers in Psychological Research: Advanced Topics"},
            {"code": "PSYC08H3", "title": "Advanced Data Analysis in Psychology"},
            {"code": "PSYC09H3", "title": "Applied Multiple Regression in Psychology"},
            {"code": "PSYC10H3", "title": "Judgment and Decision Making"},
            {"code": "PSYC12H3", "title": "The Psychology of Prejudice"},
            {"code": "PSYC13H3", "title": "Social Cognition: Understanding Ourselves and Others"},
            {"code": "PSYC14H3", "title": "Cross-Cultural Social Psychology"},
            {"code": "PSYC15H3", "title": "Foundations in Community Psychology"},
            {"code": "PSYC16H3", "title": "Psychology of Imagination"},
            {"code": "PSYC17H3", "title": "Meeting Minds: The Psychology of Interpersonal Interactions"},
            {"code": "PSYC18H3", "title": "The Psychology of Emotion"},
            {"code": "PSYC19H3", "title": "Psychology of Self Control"},
            {"code": "PSYC21H3", "title": "Adulthood and Aging"},
            {"code": "PSYC22H3", "title": "Infancy"},
            {"code": "PSYC23H3", "title": "Developmental Psychobiology"},
            {"code": "PSYC24H3", "title": "Childhood and Adolescence"},
            {"code": "PSYC27H3", "title": "Social Development"},
            {"code": "PSYC28H3", "title": "Emotional Development"},
            {"code": "PSYC30H3", "title": "Advanced Personality Psychology"},
            {"code": "PSYC31H3", "title": "Neuropsychological Assessment"},
            {"code": "PSYC34H3", "title": "The Psychology of Happiness and Meaning"},
            {"code": "PSYC36H3", "title": "Psychotherapy"},
            {"code": "PSYC37H3", "title": "Psychological Assessment"},
            {"code": "PSYC38H3", "title": "Adult Psychopathology"},
            {"code": "PSYC39H3", "title": "Psychology and the Law"},
            {"code": "PSYC50H3", "title": "Higher-Level Cognition"},
            {"code": "PSYC51H3", "title": "Cognitive Neuroscience of Vision"},
            {"code": "PSYC52H3", "title": "Cognitive Neuroscience of Attention"},
            {"code": "PSYC53H3", "title": "Cognitive Neuroscience of Memory"},
            {"code": "PSYC54H3", "title": "Auditory Cognitive Neuroscience"},
            {"code": "PSYC56H3", "title": "Music Cognition"},
            {"code": "PSYC57H3", "title": "Cognitive Neuroscience of Decision Making"},
            {"code": "PSYC59H3", "title": "Cognitive Neuroscience of Language"},
            {"code": "PSYC62H3", "title": "Drugs and the Brain"},
            {"code": "PSYC70H3", "title": "Advanced Research Methods Laboratory"},
            {"code": "PSYC71H3", "title": "Social Psychology Laboratory"},
            {"code": "PSYC72H3", "title": "Developmental Psychology Laboratory"},
            {"code": "PSYC73H3", "title": "Wellness and Resilience Laboratory"},
            {"code": "PSYC74H3", "title": "Human Movement Laboratory"},
            {"code": "PSYC75H3", "title": "Cognitive Psychology Laboratory"},
            {"code": "PSYC76H3", "title": "Brain Imaging Laboratory"},
            {"code": "PSYC81H3", "title": "Psychology for Sustainability"},
            {"code": "PSYC85H3", "title": "History of Psychology"},
            {"code": "PSYC86H3", "title": "The Unconscious Mind"},
            {"code": "PSYC87H3", "title": "Psychology and Money"},
            {"code": "PSYC90H3", "title": "Supervised Study in Psychology"},
            {"code": "PSYC93H3", "title": "Supervised Study in Psychology"},
            {"code": "PSYD10H3", "title": "Community and Applied Social Psychology"},
            {"code": "PSYD13H3", "title": "The Psychology of Emotion Regulation"},
            {"code": "PSYD14H3", "title": "Psychology of Morality"},
            {"code": "PSYD15H3", "title": "Current Topics in Social Psychology"},
            {"code": "PSYD16H3", "title": "Critical Analysis in Social Psychology"},
            {"code": "PSYD17H3", "title": "Social Neuroscience"},
            {"code": "PSYD18H3", "title": "Psychology of Gender"},
            {"code": "PSYD19H3", "title": "The Science of Behaviour Change"},
            {"code": "PSYD20H3", "title": "Current Topics in Developmental Psychology"},
            {"code": "PSYD22H3", "title": "Socialization Processes"},
            {"code": "PSYD23H3", "title": "Dyadic Processes in Psychological Development"},
            {"code": "PSYD24H3", "title": "Seeing, Hearing, and Moving in Children"},
            {"code": "PSYD28H3", "title": "The Development of Affective Cognition"},
            {"code": "PSYD30H3", "title": "Current Topics in Personality Psychology"},
            {"code": "PSYD31H3", "title": "Cultural-Clinical Psychology"},
            {"code": "PSYD32H3", "title": "Personality Disorders"},
            {"code": "PSYD33H3", "title": "Current Topics in Clinical Psychology"},
            {"code": "PSYD35H3", "title": "Clinical Psychopharmacology"},
            {"code": "PSYD37H3", "title": "Social Context of Mental Health and Illness"},
            {"code": "PSYD39H3", "title": "Cognitive Behavioural Therapy"},
            {"code": "PSYD50H3", "title": "Current Topics in Memory and Cognition"},
            {"code": "PSYD51H3", "title": "Current Topics in Perception"},
            {"code": "PSYD52H3", "title": "Neural Network Models of Cognition Laboratory"},
            {"code": "PSYD54H3", "title": "Current Topics in Visual Recognition"},
            {"code": "PSYD55H3", "title": "Functional Magnetic Resonance Imaging Laboratory"},
            {"code": "PSYD59H3", "title": "Psychology of Gambling"},
            {"code": "PSYD62H3", "title": "Neuroscience of Pleasure and Reward"},
            {"code": "PSYD66H3", "title": "Current Topics in Human Brain and Behaviour"},
            {"code": "PSYD98H3", "title": "Thesis in Psychology"},
            {"code": "PHYA10H3", "title": "Physics I for the Physical Sciences"},
            {"code": "PHYA11H3", "title": "Physics I for the Life Sciences"},
            {"code": "PHYA21H3", "title": "Physics II for the Physical Sciences"},
            {"code": "PHYA22H3", "title": "Physics II for the Life Sciences"},
            {"code": "PHYB01H3", "title": "Modern Physics for Non-Scientists"},
            {"code": "PHYB10H3", "title": "Intermediate Physics Laboratory I"},
            {"code": "PHYB21H3", "title": "Electricity and Magnetism"},
            {"code": "PHYB52H3", "title": "Thermal Physics"},
            {"code": "PHYB54H3", "title": "Mechanics: From Oscillations to Chaos"},
            {"code": "PHYB56H3", "title": "Introduction to Quantum Physics"},
            {"code": "PHYB57H3", "title": "Introduction to Scientific Computing"},
            {"code": "PHYC11H3", "title": "Intermediate Physics Laboratory II"},
            {"code": "PHYC14H3", "title": "Introduction to Atmospheric Physics"},
            {"code": "PHYC50H3", "title": "Electromagnetic Theory"},
            {"code": "PHYC54H3", "title": "Classical Mechanics"},
            {"code": "PHYC56H3", "title": "Quantum Mechanics I"},
            {"code": "PHYC83H3", "title": "Introduction to General Relativity"},
            {"code": "PHYD01H3", "title": "Research Project in Physics and Astrophysics"},
            {"code": "PHYD02Y3", "title": "Extended Research Project in Physics and Astrophysics"},
            {"code": "PHYD26H3", "title": "Planetary Geophysics"},
            {"code": "PHYD27H3", "title": "Physics of Climate Modeling"},
            {"code": "PHYD28H3", "title": "Introduction to Magnetohydrodynamics for Astrophysics and Geophysics"},
            {"code": "PHYD37H3", "title": "Introduction to Fluid Mechanics"},
            {"code": "PHYD38H3", "title": "Nonlinear Systems and Chaos"},
            {"code": "PHYD57H3", "title": "Advanced Computational Methods in Physics"},
            {"code": "PHYD72H3", "title": "Supervised Reading in Physics and Astrophysics"},
            {"code": "CHMA10H3", "title": "Introductory Chemistry I: Structure and Bonding"},
            {"code": "CHMA11H3", "title": "Introductory Chemistry II: Reactions and Mechanisms"},
            {"code": "CHMA12H3", "title": "Advanced General Chemistry"},
            {"code": "CHMB16H3", "title": "Techniques in Analytical Chemistry"},
            {"code": "CHMB20H3", "title": "Chemical Thermodynamics and Elementary Kinetics"},
            {"code": "CHMB21H3", "title": "Chemical Structure and Spectroscopy"},
            {"code": "CHMB23H3", "title": "Introduction to Chemical Thermodynamics and Kinetics: Theory and Practice"},
            {"code": "CHMB31H3", "title": "Introduction to Inorganic Chemistry"},
            {"code": "CHMB41H3", "title": "Organic Chemistry I"},
            {"code": "CHMB42H3", "title": "Organic Chemistry II"},
            {"code": "CHMB43Y3", "title": "Organic Chemistry I and II"},
            {"code": "CHMB55H3", "title": "Environmental Chemistry"},
            {"code": "CHMB62H3", "title": "Introduction to Biochemistry"},
            {"code": "CHMC11H3", "title": "Principles of Analytical Instrumentation"},
            {"code": "CHMC16H3", "title": "Analytical Instrumentation"},
            {"code": "CHMC20H3", "title": "Intermediate Physical Chemistry"},
            {"code": "CHMC21H3", "title": "Topics in Biophysical Chemistry"},
            {"code": "CHMC31Y3", "title": "Intermediate Inorganic Chemistry"},
            {"code": "CHMC42H3", "title": "Organic Synthesis"},
            {"code": "CHMC47H3", "title": "Bio-Organic Chemistry"},
            {"code": "CHMC71H3", "title": "Medicinal Chemistry"},
            {"code": "CHMD11H3", "title": "Application of Spectroscopy in Chemical Structure Determination"},
            {"code": "CHMD16H3", "title": "Environmental and Analytical Chemistry"},
            {"code": "CHMD39H3", "title": "Topics in Inorganic Chemistry"},
            {"code": "CHMD41H3", "title": "Physical Organic Chemistry"},
            {"code": "CHMD47H3", "title": "Advanced Bio-Organic Chemistry"},
            {"code": "CHMD59H3", "title": "Modelling the Fate of Organic Chemicals in the Environment"},
            {"code": "CHMD69H3", "title": "Bioinorganic Chemistry"},
            {"code": "CHMD79H3", "title": "Topics in Biological Chemistry"},
            {"code": "CHMD89H3", "title": "Introduction to Green Chemistry"},
            {"code": "CHMD90Y3", "title": "Directed Research"},
            {"code": "CHMD91H3", "title": "Directed Research"},
            {"code": "CHMD92H3", "title": "Advanced Chemistry Laboratory Course"},
            {"code": "ACTB40H3", "title": "Fundamentals of Investment and Credit"},
            {"code": "STAA57H3", "title": "Introduction to Data Science"},
            {"code": "STAB22H3", "title": "Statistics I"},
            {"code": "STAB23H3", "title": "Introduction to Statistics for the Social Sciences"},
            {"code": "STAB27H3", "title": "Statistics II"},
            {"code": "STAB41H3", "title": "Financial Derivatives"},
            {"code": "STAB52H3", "title": "An Introduction to Probability"},
            {"code": "STAB53H3", "title": "Introduction to Applied Probability"},
            {"code": "STAB57H3", "title": "An Introduction to Statistics"},
            {"code": "STAC32H3", "title": "Applications of Statistical Methods"},
            {"code": "STAC33H3", "title": "Introduction to Applied Statistics"},
            {"code": "STAC50H3", "title": "Data Collection"},
            {"code": "STAC51H3", "title": "Categorical Data Analysis"},
            {"code": "STAC53H3", "title": "Applied Data Collection"},
            {"code": "STAC58H3", "title": "Statistical Inference"},
            {"code": "STAC62H3", "title": "Probability and Stochastic Processes I"},
            {"code": "STAC63H3", "title": "Probability and Stochastic Processes II"},
            {"code": "STAC67H3", "title": "Regression Analysis"},
            {"code": "STAC70H3", "title": "Statistics and Finance I"},
            {"code": "STAD29H3", "title": "Statistics for Life & Social Scientists"},
            {"code": "STAD37H3", "title": "Multivariate Analysis"},
            {"code": "STAD57H3", "title": "Time Series Analysis"},
            {"code": "STAD68H3", "title": "Advanced Machine Learning and Data Mining"},
            {"code": "STAD70H3", "title": "Statistics and Finance II"},
            {"code": "STAD78H3", "title": "Machine Learning Theory"},
            {"code": "STAD80H3", "title": "Analysis of Big Data"},
            {"code": "STAD81H3", "title": "Causal Inference"},
            {"code": "STAD91H3", "title": "Topics in Statistics"},
            {"code": "STAD92H3", "title": "Readings in Statistics"},
            {"code": "STAD93H3", "title": "Readings in Statistics"},
            {"code": "STAD94H3", "title": "Statistics Project"},
            {"code": "STAD95H3", "title": "Statistics Project"},
            {"code": "ACMA01H3", "title": "Exploring Key Questions in the Arts, Culture and Media"},
            {"code": "ACMB10H3", "title": "Equity and Diversity in the Arts"},
            {"code": "ACMC01H3", "title": "ACMEE Applied Practice I"},
            {"code": "ACMD01H3", "title": "ACMEE Applied Practice II"},
            {"code": "ACMD02H3", "title": "ACMEE Applied Practice III"},
            {"code": "ACMD91H3", "title": "Supervised Readings"},
            {"code": "ACMD92H3", "title": "Supervised Readings"},
            {"code": "ACMD93Y3", "title": "Supervised Readings"},
            {"code": "ACMD94H3", "title": "Senior Collaboration Project in Arts, Culture and Media"},
            {"code": "ACMD98H3", "title": "Experiential Learning for Arts, Culture and Media Programs"},
            {"code": "ACMD99H3", "title": "Work Integrated Learning for Arts Culture and Media Programs"},
            {"code": "ACTB40H3", "title": "Fundamentals of Investment and Credit"},
            {"code": "AFSA01H3", "title": "Africa in the World: An Introduction"},
            {"code": "AFSA03H3", "title": "Experiencing Development in Africa"},
            {"code": "AFSB01H3", "title": "African Religious Traditions Through History"},
            {"code": "AFSB05H3", "title": "Culture and Society in Africa"},
            {"code": "AFSB50H3", "title": "Africa in the Era of the Slave Trade"},
            {"code": "AFSB51H3", "title": "Africa from the Colonial Conquests to Independence"},
            {"code": "AFSB54H3", "title": "Africa in the Postcolonial Era"},
            {"code": "AFSC03H3", "title": "Contemporary Africa: State, Society, and Politics"},
            {"code": "AFSC19H3", "title": "Community-Driven Development: Cooperatives, Social Enterprises and the Black Social Economy"},
            {"code": "AFSC52H3", "title": "Ethiopia: Seeing History"},
            {"code": "AFSC53H3", "title": "Gender and Critical Development"},
            {"code": "AFSC55H3", "title": "War and Society in Modern Africa"},
            {"code": "AFSC70H3", "title": "The Caribbean Diaspora"},
            {"code": "AFSC97H3", "title": "Women and Power in Africa"},
            {"code": "AFSD07H3", "title": "Extractive Industries in Africa"},
            {"code": "AFSD16H3", "title": "Africana Political Economy in Comparative Perspective"},
            {"code": "AFSD20H3", "title": "Thinking Conflict, Security, and Development"},
            {"code": "AFSD51H3", "title": "Southern Africa: Colonial Rule, Apartheid and Liberation"},
            {"code": "AFSD52H3", "title": "East African Societies in Transition"},
            {"code": "AFSD53H3", "title": "Africa and Asia in the First World War"},
            {"code": "ANTA01H3", "title": "Introduction to Anthropology: Becoming Human"},
            {"code": "ANTA02H3", "title": "Introduction to Anthropology: Society, Culture and Language"},
            {"code": "ANTB01H3", "title": "Political Ecology"},
            {"code": "ANTB02H3", "title": "The Body in Culture and Society"},
            {"code": "ANTB05H3", "title": "Culture and Society in Africa"},
            {"code": "ANTB09H3", "title": "Culture through Film and Media"},
            {"code": "ANTB11H3", "title": "World Prehistory"},
            {"code": "ANTB12H3", "title": "Anthropology of Science Fiction"},
            {"code": "ANTB14H3", "title": "Evolutionary Anthropology"},
            {"code": "ANTB15H3", "title": "Contemporary Human Evolution and Variation"},
            {"code": "ANTB16H3", "title": "Canadian Cultural Identities"},
            {"code": "ANTB18H3", "title": "Development, Inequality and Social Change in Latin America"},
            {"code": "ANTB19H3", "title": "Ethnography and the Comparative Study of Human Societies"},
            {"code": "ANTB20H3", "title": "Ethnography and the Global Contemporary"},
            {"code": "ANTB22H3", "title": "Primate Behaviour"},
            {"code": "ANTB26H3", "title": "The Middle East and North Africa: Past and Present"},
            {"code": "ANTB33H3", "title": "The Future of Work"},
            {"code": "ANTB35H3", "title": "Kids These Days: Youth, Language and Media"},
            {"code": "ANTB36H3", "title": "Anthropology of the End of the World"},
            {"code": "ANTB42H3", "title": "Culture and Society in Contemporary South Asia"},
            {"code": "ANTB64H3", "title": "Are You What You Eat?: The Anthropology of Food"},
            {"code": "ANTB65H3", "title": "An Introduction to Pacific Island Societies"},
            {"code": "ANTB66H3", "title": "Spiritual Paths: A Comparative Anthropology of Pilgrimage"},
            {"code": "ANTB80H3", "title": "Introduction to Archaeology: Methods, Theories, and Practices"},
            {"code": "ANTC03H3", "title": "Directed Reading in Anthropology"},
            {"code": "ANTC04H3", "title": "Directed Reading in Anthropology"},
            {"code": "ANTC07H3", "title": "Material Worlds"},
            {"code": "ANTC09H3", "title": "Sex, Love, and Intimacy: Anthropological Approaches to Kinship and Marriage"},
            {"code": "ANTC10H3", "title": "Anthropological Perspectives on Development"},
            {"code": "ANTC14H3", "title": "Feminism and Anthropology"},
            {"code": "ANTC15H3", "title": "Genders and Sexualities"},
            {"code": "ANTC16H3", "title": "The Foundation and Theory of Human Origins"},
            {"code": "ANTC17H3", "title": "Human Origins: New Discoveries"},
            {"code": "ANTC18H3", "title": "Urban Worlds"},
            {"code": "ANTC19H3", "title": "Producing People and Things: Economics and Social Life"},
            {"code": "ANTC20H3", "title": "Gifts, Money and Morality"},
            {"code": "ANTC22H3", "title": "Education, Power, and Potential: Anthropological Perspectives and Ethnographic Insights"},
            {"code": "ANTC24H3", "title": "Culture, Mental Illness, and Psychiatry"},
            {"code": "ANTC25H3", "title": "Anthropology and Psychology"},
            {"code": "ANTC27H3", "title": "Primate Sociality"},
            {"code": "ANTC29H3", "title": "Archaeologies of North America"},
            {"code": "ANTC30H3", "title": "Themes in Global Archaeology"},
            {"code": "ANTC31H3", "title": "Ritual and Religious Action"},
            {"code": "ANTC32H3", "title": "Political Anthropology"},
            {"code": "ANTC33H3", "title": "Of Gods and Humans: Anthropological Approaches to Religion"},
            {"code": "ANTC34H3", "title": "The Anthropology of Transnationalism"},
            {"code": "ANTC35H3", "title": "Quantitative Methods in Anthropology"},
            {"code": "ANTC40H3", "title": "Methods and Analysis in Anthropological Demography"},
            {"code": "ANTC41H3", "title": "Environmental Stress, Culture and Human Adaptability"},
            {"code": "ANTC42H3", "title": "Human Growth, Development and Adaptability"},
            {"code": "ANTC44H3", "title": "Amazonian Anthropology"},
            {"code": "ANTC47H3", "title": "Human and Primate Comparative Osteology"},
            {"code": "ANTC48H3", "title": "Advanced Topics In Human Osteology"},
            {"code": "ANTC52H3", "title": "Global Politics of Language"},
            {"code": "ANTC53H3", "title": "Anthropology of Media and Publics"},
            {"code": "ANTC58H3", "title": "Constructing the Other: Orientalism through Time and Place"},
            {"code": "ANTC59H3", "title": "Anthropology of Language and Media"},
            {"code": "ANTC61H3", "title": "Medical Anthropology: Illness and Healing in Cultural Perspective"},
            {"code": "ANTC62H3", "title": "Medical Anthropology: Biological and Demographic Perspectives"},
            {"code": "ANTC65H3", "title": "Anthropology of Science, Medicine, and Technology"},
            {"code": "ANTC66H3", "title": "Anthropology of Tourism"},
            {"code": "ANTC67H3", "title": "Foundations in Epidemiology"},
            {"code": "ANTC68H3", "title": "Deconstructing Epidemics"},
            {"code": "ANTC69H3", "title": "Ideas That Matter: Key Themes and Thinkers in Anthropology"},
            {"code": "ANTC70H3", "title": "Ethnographic Methods in Anthropology: Past, Present, and Future"},
            {"code": "ANTC71H3", "title": "Climate, Palaeoecology, and Policy: Archaeology of Humans in the Environment"},
            {"code": "ANTC80H3", "title": "Race and Racism: Anthropological Insights"},
            {"code": "ANTC88H3", "title": "Special Topics"},
            {"code": "ANTC99H3", "title": "Primate Evolution"},
            {"code": "ANTD04H3", "title": "The Anthropology of Violence and Suffering"},
            {"code": "ANTD05H3", "title": "Advanced Fieldwork Methods in Social and Cultural Anthropology"},
            {"code": "ANTD06H3", "title": "Reading Ethnography"},
            {"code": "ANTD07H3", "title": "Advanced Regional Seminar"},
            {"code": "ANTD10H3", "title": "The Anthropology of 'Life' Itself"},
            {"code": "ANTD13H3", "title": "Frontiers of Anthropology: A Biological Perspective"},
            {"code": "ANTD15H3", "title": "Frontiers of Socio-Cultural Anthropology"},
            {"code": "ANTD16H3", "title": "Biomedical Anthropology"},
            {"code": "ANTD17H3", "title": "Medical Osteology: Public Health Perspectives on Human Skeletal Health"},
            {"code": "ANTD18H3", "title": "Palaeolithic Archaeology"},
            {"code": "ANTD19H3", "title": "Primate Conservation"},
            {"code": "ANTD20H3", "title": "Culture and Community"},
            {"code": "ANTD22H3", "title": "Theory and Methodology in Primatology"},
            {"code": "ANTD25H3", "title": "Medical Primatology: Public Health Perspectives on Zoonotic Diseases"},
            {"code": "ANTD26H3", "title": "Caveman, Farmer, Herder, Trader: Evolution of Diet in Society"},
            {"code": "ANTD31H3", "title": "Advanced Research in Anthropology"},
            {"code": "ANTD32H3", "title": "Advanced Research in Anthropology"},
            {"code": "ANTD33H3", "title": "Geoarchaeological Perspectives of Human-Environment Interactions"},
            {"code": "ANTD35H3", "title": "Bioarchaeology"},
            {"code": "ANTD40H3", "title": "Topics in Emerging Scholarship in Evolutionary Anthropology"},
            {"code": "ANTD41H3", "title": "Topics in Emerging Scholarship in Socio-Cultural Anthropology"},
            {"code": "ANTD60H3", "title": "Advanced Archaeological Laboratory Methods"},
            {"code": "ANTD70H3", "title": "Archaeological Field Methods"},
            {"code": "ANTD71H3", "title": "Community Engaged Fieldwork with Food"},
            {"code": "ANTD98H3", "title": "Advanced Topics in Socio-Cultural Anthropology"},
            {"code": "ANTD99H3", "title": "Advanced Topics in Primate Evolution"},
            {"code": "ASTA01H3", "title": "Introduction to Astronomy and Astrophysics I: The Sun and Planets"},
            {"code": "ASTA02H3", "title": "Introduction to Astronomy and Astrophysics II: Beyond the Sun and Planets"},
            {"code": "ASTB03H3", "title": "Great Moments in Astronomy"},
            {"code": "ASTB23H3", "title": "Astrophysics of Stars, Galaxies and the Universe"},
            {"code": "ASTC02H3", "title": "Practical Astronomy: Instrumentation and Data Analysis"},
            {"code": "ASTC25H3", "title": "Astrophysics of Planetary Systems"},
            {"code": "CITA01H3", "title": "Foundations of City Studies"},
            {"code": "CITA02H3", "title": "Studying Cities"},
            {"code": "CITB01H3", "title": "Canadian Cities and Planning"},
            {"code": "CITB03H3", "title": "Social Planning and Community Development"},
            {"code": "CITB04H3", "title": "City Politics"},
            {"code": "CITB05H3", "title": "Researching the City: An Introduction to Methods"},
            {"code": "CITB07H3", "title": "Introduction to Global Urbanisms"},
            {"code": "CITB08H3", "title": "Economy of Cities"},
            {"code": "CITC01H3", "title": "Urban Communities and Neighbourhoods Case Study: East Scarborough"},
            {"code": "CITC02H3", "title": "Placements in Community Development"},
            {"code": "CITC03H3", "title": "Housing Policy and Planning"},
            {"code": "CITC04H3", "title": "Current Municipal and Planning Policy and Practice in Toronto"},
            {"code": "CITC07H3", "title": "Urban Social Policy"},
            {"code": "CITC08H3", "title": "Cities and Community Development"},
            {"code": "CITC09H3", "title": "Introduction to Planning History: Toronto and Its Region"},
            {"code": "CITC10H3", "title": "Selected Issues in City Studies"},
            {"code": "CITC12H3", "title": "City Structures, Problems, and Decisions: Field Research in Urban Policy Making"},
            {"code": "CITC14H3", "title": "Environmental Planning"},
            {"code": "CITC15H3", "title": "Money Matters: How Municipal Finance Shapes the City"},
            {"code": "CITC16H3", "title": "Planning and Governing the Metropolis"},
            {"code": "CITC17H3", "title": "Civic Engagement in Urban Politics"},
            {"code": "CITC18H3", "title": "Urban Transportation Policy Analysis"},
            {"code": "CITC54H3", "title": "City Studies Field Trip Course"},
            {"code": "CITD01H3", "title": "City Issues and Strategies"},
            {"code": "CITD05H3", "title": "City Studies Workshop I"},
            {"code": "CITD06H3", "title": "City Studies Workshop II"},
            {"code": "CITD10H3", "title": "Seminar in Selected Issues in City Studies"},
            {"code": "CITD12H3", "title": "Planning and Building Public Spaces in Toronto"},
            {"code": "CITD30H3", "title": "Supervised Research Project"},
            {"code": "CLAA04H3", "title": "The Ancient Mediterranean World"},
            {"code": "CLAA05H3", "title": "Ancient Mythology I: Mesopotamia and Egypt"},
            {"code": "CLAA06H3", "title": "Ancient Mythology II: Greece and Rome"},
            {"code": "CLAB05H3", "title": "History and Culture of the Greek World"},
            {"code": "CLAB06H3", "title": "History and Culture of the Roman World"},
            {"code": "CLAB09H3", "title": "Between Two Empires: The World of Late Antiquity"},
            {"code": "CLAB20H3", "title": "The Ancient World in Film"},
            {"code": "CLAC01H3", "title": "Selected Topics in Classical Literature"},
            {"code": "CLAC02H3", "title": "Selected Topics in Classical Civilization"},
            {"code": "CLAC05H3", "title": "Beyond Cleopatra: Decolonial Approaches to Ancient Egypt"},
            {"code": "CLAC11H3", "title": "Classical Literature I: Poetry"},
            {"code": "CLAC12H3", "title": "Classical Literature II: Prose"},
            {"code": "CLAC22H3", "title": "Religions of the Ancient Mediterranean"},
            {"code": "CLAC24H3", "title": "Race and Ethnicity in the Ancient Mediterranean and West Asian Worlds"},
            {"code": "CLAC26H3", "title": "Indigeneity and the Classics"},
            {"code": "CLAC67H3", "title": "Early Islam: Perspectives on the Construction of a Historical Tradition"},
            {"code": "CLAC68H3", "title": "Constructing the Other: Orientalism through Time and Place"},
            {"code": "CLAC94H3", "title": "The Bible and the Quran"},
            {"code": "CLAD05H3", "title": "Dripping Histories: Water in the Ancient Mediterranean and West Asian Worlds"},
            {"code": "CLAD69H3", "title": "Sufis and Desert Fathers: Mysticism in Late Antiquity and Early Islam"},
            {"code": "CRTB01H3", "title": "Introduction to Curating Art"},
            {"code": "CRTC72H3", "title": "Art, the Museum, and the Gallery"},
            {"code": "CRTC80H3", "title": "Curator as Artist; Artist as Curator"},
            {"code": "CRTD43H3", "title": "Curating Contemporary Art"},
            {"code": "CRTD44H3", "title": "Curating Historical Art"},
            {"code": "CTLA01H3", "title": "Foundations in Effective Academic Communication"},
            {"code": "CTLA02H3", "title": "Exploring Inter-Cultural Perspectives in Academic Contexts"},
            {"code": "CTLA20H3", "title": "Writing for Change: Foundational Academic Skills to Make a Difference in Your Community"},
            {"code": "CTLA21H3", "title": "Math4life: Developing Mathematical Thinking and Skills in Practical Contexts"},
            {"code": "CTLB03H3", "title": "Introduction to Community Engaged Learning"},
            {"code": "DTSB01H3", "title": "Introduction to Diaspora and Transnational Studies I"},
            {"code": "DTSB02H3", "title": "Introduction to Diaspora and Transnational Studies II"},
            {"code": "ECTB58H3", "title": "Foundations of Translation"},
            {"code": "ECTB60H3", "title": "Agri-Food, Cultures, and Translation"},
            {"code": "ECTB61H3", "title": "English and Chinese Translation: Theory and Practice"},
            {"code": "ECTB66H3", "title": "English and Chinese Interpreting Skills and Practices"},
            {"code": "ECTB71H3", "title": "Medical Terminology, Translation and Interpretation I"},
            {"code": "ECTC60H3", "title": "Translation and Gender"},
            {"code": "ECTC61H3", "title": "Translation Studies in Literature"},
            {"code": "ECTC62H3", "title": "Translation in Media"},
            {"code": "ECTC63H3", "title": "Translation and the Environment"},
            {"code": "ECTC64H3", "title": "Translating Cultures in a Polarizing World"},
            {"code": "ECTC65H3", "title": "Translation and Religion"},
            {"code": "ECTC66H3", "title": "History of Translation"},
            {"code": "ECTC67H3", "title": "Special Topics in Translation"},
            {"code": "ECTD60H3", "title": "Translating Modernity"},
            {"code": "ECTD63H3", "title": "Cultural Translation and Interpretation"},
            {"code": "ECTD65H3", "title": "Translation Studies and Theory After the Cultural Turn"},
            {"code": "ECTD66H3", "title": "Translation and Adaptation"},
            {"code": "ECTD67H3", "title": "Translation and the Arts"},
            {"code": "ECTD68H3", "title": "Translation for Business"},
            {"code": "ECTD69H3", "title": "Translation for Government and Public Administration"},
            {"code": "ECTD70H3", "title": "Transcultural Translations of the Wild"},
            {"code": "EESA01H3", "title": "Introduction to Environmental Science"},
            {"code": "EESA06H3", "title": "Introduction to Planet Earth"},
            {"code": "EESA07H3", "title": "Water"},
            {"code": "EESA09H3", "title": "Wind"},
            {"code": "EESA10H3", "title": "Human Health and the Environment"},
            {"code": "EESA11H3", "title": "Environmental Pollution"},
            {"code": "EESB02H3", "title": "Principles of Geomorphology"},
            {"code": "EESB03H3", "title": "Principles of Climatology"},
            {"code": "EESB04H3", "title": "Principles of Hydrology"},
            {"code": "EESB05H3", "title": "Principles of Soil Science"},
            {"code": "EESB15H3", "title": "Earth History"},
            {"code": "EESB16H3", "title": "Feeding Humans - The Cost to the Planet"},
            {"code": "EESB17H3", "title": "Hydro Politics and Transboundary Water Resources Management"},
            {"code": "EESB18H3", "title": "Natural Hazards"},
            {"code": "EESB19H3", "title": "Mineralogy"},
            {"code": "EESB20H3", "title": "Sedimentology and Stratigraphy"},
            {"code": "EESB22H3", "title": "Environmental Geophysics"},
            {"code": "EESB26H3", "title": "Introduction to Global Geophysics"},
            {"code": "EESC02H3", "title": "Invaded Environments"},
            {"code": "EESC03H3", "title": "Geographic Information Systems and Remote Sensing"},
            {"code": "EESC04H3", "title": "Biodiversity and Biogeography"},
            {"code": "EESC07H3", "title": "Groundwater"},
            {"code": "EESC13H3", "title": "Environmental Impact Assessment and Auditing"},
            {"code": "EESC16H3", "title": "Field Camp I"},
            {"code": "EESC18H3", "title": "Limnology"},
            {"code": "EESC19H3", "title": "Oceanography"},
            {"code": "EESC20H3", "title": "Geochemistry"},
            {"code": "EESC22H3", "title": "Exploration Geophysics"},
            {"code": "EESC24H3", "title": "Advanced Readings in Environmental Science"},
            {"code": "EESC25H3", "title": "Urban Climatology"},
            {"code": "EESC26H3", "title": "Seismology and Seismic Methods"},
            {"code": "EESC30H3", "title": "Environmental Microbiology"},
            {"code": "EESC31H3", "title": "Glacial Geology"},
            {"code": "EESC33H3", "title": "Environmental Science Field Course"},
            {"code": "EESC34H3", "title": "Sustainability in Practice"},
            {"code": "EESC36H3", "title": "Petrology"},
            {"code": "EESC37H3", "title": "Structural Geology"},
            {"code": "EESC38H3", "title": "The Anthropocene"},
            {"code": "EESD02H3", "title": "Contaminant Hydrogeology"},
            {"code": "EESD06H3", "title": "Climate Change Impact Assessment"},
            {"code": "EESD07H3", "title": "Field Camp II"},
            {"code": "EESD09H3", "title": "Research Project in Environmental Science"},
            {"code": "EESD10Y3", "title": "Research Project in Environmental Science"},
            {"code": "EESD11H3", "title": "Advanced Watershed Hydrology"},
            {"code": "EESD13H3", "title": "Environmental Law, Policy and Ethics"},
            {"code": "EESD15H3", "title": "Fundamentals of Site Remediation"},
            {"code": "EESD17Y3", "title": "Cohort Capstone Course in Environmental Studies"},
            {"code": "EESD18H3", "title": "Environmental Studies Seminar Series"},
            {"code": "EESD19H3", "title": "Professional Development Seminars in Geoscience"},
            {"code": "EESD20H3", "title": "Geological Evolution and Environmental History of North America"},
            {"code": "EESD21H3", "title": "Geophysical and Climate Data Analysis"},
            {"code": "EESD28H3", "title": "Fundamentals of Environmental Modelling"},
            {"code": "EESD31H3", "title": "Applied Climatology"},
            {"code": "EESD33H3", "title": "Field Techniques"},
            {"code": "ENGA01H3", "title": "What Is Literature?"},
            {"code": "ENGA02H3", "title": "Critical Writing about Literature"},
            {"code": "ENGA03H3", "title": "Introduction to Creative Writing"},
            {"code": "ENGA10H3", "title": "Literature and Film for Our Time: Visions and Revisions"},
            {"code": "ENGA11H3", "title": "Literature and Film for Our Time: Dawn of the Digital"},
            {"code": "ENGB01H3", "title": "Introduction to Indigenous Literatures of Turtle Island"},
            {"code": "ENGB02H3", "title": "Effective Writing in the Sciences"},
            {"code": "ENGB04H3", "title": "How to Read a Poem"},
            {"code": "ENGB06H3", "title": "Canadian Literature to 1900"},
            {"code": "ENGB07H3", "title": "Canadian Literature 1900 to Present"},
            {"code": "ENGB08H3", "title": "American Literature to 1860"},
            {"code": "ENGB09H3", "title": "American Literature from the Civil War to the Present"},
            {"code": "ENGB12H3", "title": "Life Writing"},
            {"code": "ENGB14H3", "title": "Twentieth-Century Drama"},
            {"code": "ENGB17H3", "title": "Contemporary Literature from the Caribbean"},
            {"code": "ENGB19H3", "title": "Contemporary Literature from South Asia"},
            {"code": "ENGB22H3", "title": "Contemporary Literature from Africa"},
            {"code": "ENGB25H3", "title": "The Canadian Short Story"},
            {"code": "ENGB26H3", "title": "Inferno"},
            {"code": "ENGB27H3", "title": "Charting Literary History I"},
            {"code": "ENGB28H3", "title": "Charting Literary History II"},
            {"code": "ENGB29H3", "title": "Shakespeare and Film"},
            {"code": "ENGB30H3", "title": "Classical Myth and Literature"},
            {"code": "ENGB31H3", "title": "The Romance: In Quest of the Marvelous"},
            {"code": "ENGB32H3", "title": "Shakespeare in Context I"},
            {"code": "ENGB33H3", "title": "Shakespeare in Context II"},
            {"code": "ENGB34H3", "title": "The Short Story"},
            {"code": "ENGB35H3", "title": "Children's Literature"},
            {"code": "ENGB37H3", "title": "Popular Literature and Mass Culture"},
            {"code": "ENGB38H3", "title": "The Graphic Novel"},
            {"code": "ENGB39H3", "title": "Tolkien's Middle Ages"},
            {"code": "ENGB50H3", "title": "Women and Literature: Forging a Tradition"},
            {"code": "ENGB52H3", "title": "Literature and Science"},
            {"code": "ENGB60H3", "title": "Creative Writing: Poetry I"},
            {"code": "ENGB61H3", "title": "Creative Writing: Fiction I"},
            {"code": "ENGB63H3", "title": "Creative Writing: Creative Nonfiction I"},
            {"code": "ENGB72H3", "title": "Advanced Critical Writing about Literature"},
            {"code": "ENGB74H3", "title": "The Body in Literature and Film"},
            {"code": "ENGB78H3", "title": "The Digital Text: From Digitized Literature to Born-Digital Works"},
            {"code": "ENGC02H3", "title": "Major Canadian Authors"},
            {"code": "ENGC03H3", "title": "Topics in Canadian Fiction"},
            {"code": "ENGC04H3", "title": "Creative Writing: Screenwriting"},
            {"code": "ENGC05H3", "title": "Creative Writing: Poetry, Experimentation, and Activism"},
            {"code": "ENGC06H3", "title": "Creative Writing: Writing for Comics"},
            {"code": "ENGC07H3", "title": "Canadian Drama"},
            {"code": "ENGC08H3", "title": "Special Topics in Creative Writing I"},
            {"code": "ENGC09H3", "title": "Canadian Poetry"},
            {"code": "ENGC10H3", "title": "Studies in Shakespeare"},
            {"code": "ENGC11H3", "title": "Poetry and Popular Culture"},
            {"code": "ENGC12H3", "title": "Individualism and Community in American Literature"},
            {"code": "ENGC13H3", "title": "Ethnic Traditions in American Literature"},
            {"code": "ENGC14H3", "title": "Black Canadian Literature"},
            {"code": "ENGC15H3", "title": "Introduction to Theory and Criticism"},
            {"code": "ENGC16H3", "title": "The Bible and Literature I"},
            {"code": "ENGC17H3", "title": "The Bible and Literature II"},
            {"code": "ENGC18H3", "title": "Colonial and Postcolonial Literature"},
            {"code": "ENGC19H3", "title": "Transnational Literature"},
            {"code": "ENGC20H3", "title": "The Antihero in Literature and Film"},
            {"code": "ENGC21H3", "title": "The Victorian Novel"},
            {"code": "ENGC22H3", "title": "Victorian Popular Fiction"},
            {"code": "ENGC23H3", "title": "Fantasy and the Fantastic in Literature and the Other Arts"},
            {"code": "ENGC24H3", "title": "Creative Writing: The Art of the Personal Essay"},
            {"code": "ENGC25H3", "title": "Victorian Poetry and Prose"},
            {"code": "ENGC26H3", "title": "Drama: Tragedy"},
            {"code": "ENGC27H3", "title": "Drama: Comedy"},
            {"code": "ENGC28H3", "title": "The Fairy Tale"},
            {"code": "ENGC29H3", "title": "Chaucer"},
            {"code": "ENGC30H3", "title": "Studies in Medieval Literature"},
            {"code": "ENGC31H3", "title": "Medieval Travel Writing"},
            {"code": "ENGC33H3", "title": "Deceit, Dissent, and the English Civil Wars, 1603-1660"},
            {"code": "ENGC34H3", "title": "Early Modern Women and Literature, 1500-1700"},
            {"code": "ENGC35H3", "title": "Imagined Communities in Early Modern England, 1500-1700"},
            {"code": "ENGC36H3", "title": "Literature and Culture, 1660-1750"},
            {"code": "ENGC37H3", "title": "Literature and Culture, 1750-1830"},
            {"code": "ENGC38H3", "title": "Novel Genres: Fiction, Journalism, News, and Autobiography, 1640-1750"},
            {"code": "ENGC39H3", "title": "The Early Novel in Context, 1740-1830"},
            {"code": "ENGC40H3", "title": "Medieval Life Writing"},
            {"code": "ENGC41H3", "title": "Video Games: Exploring the Virtual Narrative"},
            {"code": "ENGC42H3", "title": "Romanticism"},
            {"code": "ENGC43H3", "title": "Nineteenth-Century Literature and Contemporary Culture"},
            {"code": "ENGC45H3", "title": "Queer Literature and Theory"},
            {"code": "ENGC46H3", "title": "Law and Literature"},
            {"code": "ENGC47H3", "title": "Modernist Poetry"},
            {"code": "ENGC48H3", "title": "Satire"},
            {"code": "ENGC49H3", "title": "The Digital Self: Social Media & Literary Culture"},
            {"code": "ENGC50H3", "title": "Studies in Contemporary American Fiction"},
            {"code": "ENGC51H3", "title": "Contemporary Arab Women Writers"},
            {"code": "ENGC54H3", "title": "Gender and Genre"},
            {"code": "ENGC59H3", "title": "Literature and the Environment"},
            {"code": "ENGC60H3", "title": "Indigenous Drama of Turtle Island"},
            {"code": "ENGC61H3", "title": "Indigenous Poetry of Turtle Island"},
            {"code": "ENGC62H3", "title": "Indigenous Short Stories of Turtle Island"},
            {"code": "ENGC69H3", "title": "Gothic Literature"},
            {"code": "ENGC70H3", "title": "The Immigrant Experience in Literature to 1980"},
            {"code": "ENGC71H3", "title": "The Immigrant Experience in Literature since 1980"},
            {"code": "ENGC74H3", "title": "Persuasive Writing and Community-Engaged Learning"},
            {"code": "ENGC79H3", "title": "Above and Beyond: Superheroes in Fiction and Film"},
            {"code": "ENGC80H3", "title": "Modernist Narrative"},
            {"code": "ENGC86H3", "title": "Creative Writing: Poetry II"},
            {"code": "ENGC87H3", "title": "Creative Writing: Fiction II"},
            {"code": "ENGC88H3", "title": "Creative Writing: Creative Nonfiction II"},
            {"code": "ENGC89H3", "title": "Creative Writing and Performance"},
            {"code": "ENGC90H3", "title": "Topics in Classical Myth and Literature"},
            {"code": "ENGC91H3", "title": "American Realisms"},
            {"code": "ENGD02Y3", "title": "Teaching Academic Writing: Theories, Methods and Service Learning"},
            {"code": "ENGD03H3", "title": "Topics in Contemporary Literary Theory"},
            {"code": "ENGD05H3", "title": "Diasporic-Indigenous Relations on Turtle Island"},
            {"code": "ENGD07H3", "title": "Studies in Postmodern Poetry"},
            {"code": "ENGD08H3", "title": "Topics in African Literature"},
            {"code": "ENGD12H3", "title": "Topics in Life Writing"},
            {"code": "ENGD13H3", "title": "Rap Poetics"},
            {"code": "ENGD14H3", "title": "Topics in Early Modern English Literature and Culture"},
            {"code": "ENGD18H3", "title": "Topics in the Long Eighteenth Century, 1660-1830"},
            {"code": "ENGD19H3", "title": "Theoretical Approaches to Early Modern English Literature and Culture"},
            {"code": "ENGD22H3", "title": "Special Topics in Creative Writing II"},
            {"code": "ENGD26Y3", "title": "Independent Studies in Creative Writing: Poetry"},
            {"code": "ENGD27Y3", "title": "Independent Studies in Creative Writing: Prose"},
            {"code": "ENGD28Y3", "title": "Independent Studies in Creative Writing: Open Genre"},
            {"code": "ENGD29H3", "title": "Chaucer's Early Works"},
            {"code": "ENGD30H3", "title": "Topics in Medieval Literature"},
            {"code": "ENGD31H3", "title": "Medieval Afterlives"},
            {"code": "ENGD42H3", "title": "Studies in Major Modernist Writers"},
            {"code": "ENGD43H3", "title": "Topics in Romanticism, 1750-1850"},
            {"code": "ENGD48H3", "title": "Studies in Major Victorian Writers"},
            {"code": "ENGD50H3", "title": "Fake Friends and Artificial Intelligence: the Human-Robot Relationship in Literature and Culture"},
            {"code": "ENGD53H3", "title": "Studies in Popular Genres"},
            {"code": "ENGD54H3", "title": "Comparative Approaches to Literature and Culture"},
            {"code": "ENGD55H3", "title": "Literature, Politics, Revolution"},
            {"code": "ENGD57H3", "title": "Studies in Major Canadian Writers"},
            {"code": "ENGD58H3", "title": "Topics in Canadian Literature"},
            {"code": "ENGD59H3", "title": "Topics in American Poetry"},
            {"code": "ENGD60H3", "title": "Topics in American Prose"},
            {"code": "ENGD68H3", "title": "Topics in Literature and Religion"},
            {"code": "ENGD71H3", "title": "Studies in Arab North-American Literature"},
            {"code": "ENGD80H3", "title": "Women and Canadian Writing"},
            {"code": "ENGD84H3", "title": "Canadian Writing in the 21st Century"},
            {"code": "ENGD89H3", "title": "Topics in the Victorian Period"},
            {"code": "ENGD90H3", "title": "Creative Writing: Genre Bending and Other Methods of Breaking Form"},
            {"code": "ENGD94H3", "title": "Stranger Than Fiction: The Documentary Film"},
            {"code": "ENGD95H3", "title": "Creative Writing as a Profession"},
            {"code": "ENGD98Y3", "title": "Senior Essay and Capstone Seminar"},
            {"code": "ESTB01H3", "title": "Introduction to Environmental Studies"},
            {"code": "ESTB02H3", "title": "Whose Land? Indigenous-Canada-Land Relations"},
            {"code": "ESTB03H3", "title": "Back to the Land: Restoring Embodied and Affective Ways of Knowing"},
            {"code": "ESTB04H3", "title": "Addressing the Climate Crisis"},
            {"code": "ESTB05H3", "title": "Climate Science for Everyone"},
            {"code": "ESTC34H3", "title": "Sustainability in Practice"},
            {"code": "ESTC35H3", "title": "Environmental Science and Technology in Society"},
            {"code": "ESTC36H3", "title": "Knowledge, Ethics and Environmental Decision-Making"},
            {"code": "ESTC37H3", "title": "Energy and Sustainability"},
            {"code": "ESTC38H3", "title": "The Anthropocene"},
            {"code": "ESTC40H3", "title": "Technical Methods for Climate Change Mitigation"},
            {"code": "ESTD16H3", "title": "Project Management in Environmental Studies"},
            {"code": "ESTD17Y3", "title": "Cohort Capstone Course in Environmental Studies"},
            {"code": "ESTD18H3", "title": "Environmental Studies Seminar Series"},
            {"code": "ESTD19H3", "title": "Risk"},
            {"code": "ESTD20H3", "title": "Integrated Natural Resource and Climate Change Governance"},
            {"code": "FLMA70H3", "title": "How to Read a Film"},
            {"code": "FLMB71H3", "title": "Writing About Movies"},
            {"code": "FLMB75H3", "title": "Cinema and Modernity"},
            {"code": "FLMB77H3", "title": "Cinema and Colonialism"},
            {"code": "FLMB80H3", "title": "Cinema, Race, and Representation"},
            {"code": "FLMC44H3", "title": "Self and Other in Literature and Film"},
            {"code": "FLMC56H3", "title": "Literature and Media: From Page to Screen"},
            {"code": "FLMC75H3", "title": "Freaks and Geeks: Children in Contemporary Film and Media"},
            {"code": "FLMC78H3", "title": "Dystopian Visions in Fiction and Film"},
            {"code": "FLMC81H3", "title": "Topics in National Cinemas"},
            {"code": "FLMC82H3", "title": "Topics in Cinema Studies"},
            {"code": "FLMC83H3", "title": "World Cinema"},
            {"code": "FLMC84H3", "title": "Cinema and Migration"},
            {"code": "FLMC92H3", "title": "Film Theory"},
            {"code": "FLMC93H3", "title": "Gender and Sexuality at the Movies"},
            {"code": "FLMC94H3", "title": "Women Directors"},
            {"code": "FLMC95H3","title": "Indian Cinemas: Bollywood, Before and Beyond"},
            {"code": "FLMD52H3","title": "Cinema: The Auteur Theory"},
            {"code": "FLMD62H3","title": "Topics in Postcolonial Literature and Film"},
            {"code": "FLMD91H3","title": "Avant-Garde Cinema"},
            {"code": "FLMD93H3", "title": "Theoretical Approaches to Cinema"},
            {"code": "FLMD96H3","title": "Iranian Cinema"},
    {"code": "FREA01H3",
        "title": "Language Practice I"
    },
    {"code": "FREA02H3",
        "title": "Language Practice II"
    },
    { "code": "FREA90Y3",
        "title": "Intensive Introductory French"
    },
    {"code": "FREA91Y3",
        "title": "Intensive Intermediate French"
    },
    {"code": "FREA96H3",
        "title": "Introductory French I"
    },
    { "code": "FREA97H3",
        "title": "Introductory French II"
    },
    {"code": "FREA98H3",
        "title": "Intermediate French I"
    },
    {"code": "FREA99H3",
        "title": "Intermediate French II"
    },
    {"code": "FREB01H3",
        "title": "Language Practice III"
    },
    {"code": "FREB02H3",
        "title": "Language Practice IV"
    },
    {"code": "FREB08H3",
        "title": "Practical Translation I"
    },
    { "code": "FREB11H3",
        "title": "French Language in the School System"
    },
    {"code": "FREB17H3",
        "title": "Spoken French: Conversation and Pronunciation"
    },
    {"code": "FREB18H3",
        "title": "Business French"
    },
    {
        "code": "FREB20H3",
        "title": "Teaching Children's Literature in French"
    },
    {
        "code": "FREB22H3",
        "title": "The Society and Culture of Québec"
    },
    {
        "code": "FREB27H3",
        "title": "Modern France"
    },
    {
        "code": "FREB28H3",
        "title": "The Francophone World"
    },
    {
        "code": "FREB35H3",
        "title": "Francophone Literature"
    },
    {
        "code": "FREB36H3",
        "title": "The 20th Century Quebec Novel"
    },
    {
        "code": "FREB37H3",
        "title": "Contemporary Quebec Drama"
    },
    {
        "code": "FREB44H3",
        "title": "Introduction to Linguistics: French Phonetics and Phonology"
    },
    {
        "code": "FREB45H3",
        "title": "Introduction to Linguistics: French Morphology and Syntax"
    },
    {
        "code": "FREB46H3",
        "title": "History of the French Language"
    },
    {
        "code": "FREB50H3",
        "title": "Introduction to Literature in French I"
    },
    {
        "code": "FREB51H3",
        "title": "Literary History in Context: From the Middle Ages to the 17th Century"
    },
    {
        "code": "FREB55H3",
        "title": "Literary History in Context: 18th and 19th Centuries"
    },
    {
        "code": "FREB70H3",
        "title": "Introduction to Film Analysis in French"
    },
    {
        "code": "FREB84H3",
        "title": "Folktale, Myth and the Fantastic in the French-Speaking World"
    },
    {
        "code": "FREC01H3",
        "title": "Language Practice V"
    },
    {
        "code": "FREC02H3",
        "title": "Language Practice VI"
    },
    {
        "code": "FREC03H3",
        "title": "French in Action I: Practical Workshop in Theatre"
    },
    {
        "code": "FREC10H3",
        "title": "Community-Engaged Learning in the Francophone Community"
    },
    {
        "code": "FREC11H3",
        "title": "Teaching French as a Second Language"
    },
    {
        "code": "FREC18H3",
        "title": "Translation for Business and Professional Needs"
    },
    {
        "code": "FREC38H3",
        "title": "Topics in the Literature of Quebec"
    },
    {
        "code": "FREC44H3",
        "title": "French Semantics"
    },
    {
        "code": "FREC46H3",
        "title": "French Syntax"
    },
    {
        "code": "FREC47H3",
        "title": "Pidgin and Creole Languages"
    },
    {
        "code": "FREC48H3",
        "title": "Sociolinguistics of French"
    },
    {
        "code": "FREC54H3",
        "title": "Paris through the Ages"
    },
    {
        "code": "FREC57H3",
        "title": "French Fiction of the 19th Century"
    },
    {
        "code": "FREC58H3",
        "title": "Literature of the Ancien Regime"
    },
    {
        "code": "FREC63H3",
        "title": "Topics in French Literature: Encountering Foreign Cultures: Travel Writing in French"
    },
    {
        "code": "FREC64H3",
        "title": "French Fiction of the 20th and 21st Centuries"
    },
    {
        "code": "FREC70H3",
        "title": "Cinema, Movements and Genres"
    },
    {
        "code": "FREC83H3",
        "title": "Cultural Identities and Stereotypes in the French-Speaking World"
    },
    {
        "code": "FRED01H3",
        "title": "Language practice VII: Written French"
    },
    {
        "code": "FRED02H3",
        "title": "Supervised Reading"
    },
    {
        "code": "FRED03H3",
        "title": "Supervised Reading"
    },
    {
        "code": "FRED04H3",
        "title": "Supervised Reading"
    },
    {
        "code": "FRED05H3",
        "title": "Supervised Reading"
    },
    {
        "code": "FRED06H3",
        "title": "Language Practice VIII: Oral French"
    },
    {
        "code": "FRED07H3",
        "title": "Supervised Reading"
    },
    {
        "code": "FRED13H3",
        "title": "Advanced Topics in French Literature"
    },
    {
        "code": "FRED14H3",
        "title": "Advanced Topics in the Literature of Quebec"
    },
    {
        "code": "FRED28H3",
        "title": "Special Topics in Translation"
    },
    {
        "code": "FRED90Y3",
        "title": "Supervised Reading"
    },
    {
        "code": "FSTA01H3",
        "title": "Foods That Changed the World"
    },
    {
        "code": "FSTA02H3",
        "title": "Food Futures: Confronting Crises, Improving Lives"
    },
    {
        "code": "FSTB01H3",
        "title": "Methodologies in Food Studies"
    },
    {
        "code": "FSTC02H3",
        "title": "Mondo Vino: The History and Culture of Wine Around the World"
    },
    {
        "code": "FSTC05H3",
        "title": "Critical Food Studies"
    }
]
        # Add courses to the database
        for course in courses:
            Course.objects.get_or_create(code=course["code"], defaults={"title": course["title"]})

        self.stdout.write(self.style.SUCCESS("Courses added successfully."))